"""empty message

Revision ID: 4e6815f78c6d
Revises: 8600d2765eff
Create Date: 2021-05-28 20:30:17.142575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6815f78c6d'
down_revision = '8600d2765eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('externalreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('externalReferenceType', sa.String(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('baseType', sa.Integer(), nullable=True),
    sa.Column('schemaLocation', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('externalreference')
    # ### end Alembic commands ###
