"""empty message

Revision ID: 620e669a1509
Revises: 
Create Date: 2021-05-28 20:25:10.007844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620e669a1509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('aristocraticTitle', sa.String(), nullable=True),
    sa.Column('birthDate', sa.String(), nullable=True),
    sa.Column('countryofBirth', sa.String(), nullable=True),
    sa.Column('deathDate', sa.String(), nullable=True),
    sa.Column('familyName', sa.String(), nullable=False),
    sa.Column('familyName_prefix', sa.String(), nullable=False),
    sa.Column('formattedName', sa.String(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('givenName', sa.String(), nullable=False),
    sa.Column('legalName', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('maritalStatus', sa.String(), nullable=True),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('placeofBirth', sa.String(), nullable=True),
    sa.Column('preferredGivenName', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valueType', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('baseType', sa.String(), nullable=True),
    sa.Column('schemaLocation', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactmedium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('mediumType', sa.String(), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('baseType', sa.String(), nullable=False),
    sa.Column('schemaLocation', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('validforendDateTime', sa.String(), nullable=True),
    sa.Column('validforstartDateTime', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('contactType', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('emailAddress', sa.String(), nullable=True),
    sa.Column('faxNumber', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('postCode', sa.String(), nullable=True),
    sa.Column('socialNetworkId', sa.String(), nullable=True),
    sa.Column('stateOrProvince', sa.String(), nullable=True),
    sa.Column('street1', sa.String(), nullable=True),
    sa.Column('street2', sa.String(), nullable=True),
    sa.Column('baseTypeMediChar', sa.String(), nullable=True),
    sa.Column('schemaLocationMediChar', sa.String(), nullable=True),
    sa.Column('typeMediChar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactmedium')
    op.drop_table('characteristic')
    op.drop_table('individual')
    # ### end Alembic commands ###
