"""empty message

Revision ID: 767042088799
Revises: 7f73d0da62c4
Create Date: 2021-05-30 12:10:54.085521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767042088799'
down_revision = '7f73d0da62c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactmedium', sa.Column('endDateTime', sa.String(), nullable=True))
    op.add_column('contactmedium', sa.Column('startDateTime', sa.String(), nullable=True))
    op.drop_column('contactmedium', 'validforstartDateTime')
    op.drop_column('contactmedium', 'validforendDateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactmedium', sa.Column('validforendDateTime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contactmedium', sa.Column('validforstartDateTime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contactmedium', 'startDateTime')
    op.drop_column('contactmedium', 'endDateTime')
    # ### end Alembic commands ###
