"""empty message

Revision ID: 7f73d0da62c4
Revises: 4e6815f78c6d
Create Date: 2021-05-28 23:57:13.002726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f73d0da62c4'
down_revision = '4e6815f78c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('countryOfBirth', sa.String(), nullable=True))
    op.add_column('individual', sa.Column('placeOfBirth', sa.String(), nullable=True))
    op.drop_column('individual', 'countryofBirth')
    op.drop_column('individual', 'placeofBirth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('placeofBirth', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('individual', sa.Column('countryofBirth', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('individual', 'placeOfBirth')
    op.drop_column('individual', 'countryOfBirth')
    # ### end Alembic commands ###
