"""empty message

Revision ID: 8600d2765eff
Revises: 620e669a1509
Create Date: 2021-05-28 20:29:11.841796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8600d2765eff'
down_revision = '620e669a1509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('othername',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('aristocraticTitle', sa.String(), nullable=True),
    sa.Column('familyName', sa.String(), nullable=True),
    sa.Column('familyNamePrefix', sa.String(), nullable=True),
    sa.Column('formattedName', sa.String(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('givenName', sa.String(), nullable=True),
    sa.Column('legalName', sa.String(), nullable=True),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('preferredGivenName', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('validforendDateTime', sa.String(length=30), nullable=True),
    sa.Column('validforstartDateTime', sa.String(length=30), nullable=True),
    sa.Column('baseType', sa.Integer(), nullable=True),
    sa.Column('schemaLocation', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatedparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('baseType', sa.Integer(), nullable=True),
    sa.Column('schemaLocation', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_idIndiv', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('evaluatedLevel', sa.Integer(), nullable=True),
    sa.Column('skillCode', sa.Integer(), nullable=True),
    sa.Column('skillName', sa.Integer(), nullable=True),
    sa.Column('validforendDateTime', sa.String(length=30), nullable=True),
    sa.Column('validforstartDateTime', sa.String(length=30), nullable=True),
    sa.Column('baseType', sa.Integer(), nullable=True),
    sa.Column('schemaLocation', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_idIndiv'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('relatedparty')
    op.drop_table('othername')
    # ### end Alembic commands ###
