"""empty message

Revision ID: 8ecc2f29cf69
Revises: 3f0c2ca00ca3
Create Date: 2021-05-31 00:27:41.374971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecc2f29cf69'
down_revision = '3f0c2ca00ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contactmedium', 'baseType',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contactmedium', 'mediumType',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contactmedium', 'preferred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contactmedium', 'schemaLocation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contactmedium', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contactmedium', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contactmedium', 'schemaLocation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contactmedium', 'preferred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('contactmedium', 'mediumType',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contactmedium', 'baseType',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
